/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///

///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData med = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData med_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empower = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empower_fill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_fill = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
